### ISSUE TITLE
Rendering issue with large coordinate values

### ISSUE THREAD

**Issue by HakanSeven12** [coin3d/coin#371] opened 2020-03-01 21:38 UTC
FreeCAD uses Coin 4.0.0 and it has this bug: https://tracker.freecadweb.org/view.php?id=4275

As you can see in the FreeCAD bug tracker eight or nine orders of magnitude values causes wavy object effect. İs there any solution for this?

**Comment by veelo** [comment] 2020-03-02 08:13
It is not a bug, and is to be expected from single precision floating point arithmetic. Coin3D has the `SbDP...` and `SoGeo...` classes for cases where high precision is needed at large scales, which of course come at a performance cost and require more resources.

https://coin3d.github.io/Coin/html/classSoGeoOrigin.html#details
https://coin3d.github.io/Coin/html/classSbDPViewVolume.html#details

Closing this for now, feel free to reopen if needed.

Bastiaan.

**Closed by veelo** 2020-03-02 08:13 UTC

**Comment by HakanSeven12** [comment] 2020-03-03 13:16
I think SoGeoOrigin not accessible from pivy.

**Comment by luzpaz** [comment] 2020-03-20 15:10
> I think SoGeoOrigin not accessible from pivy.

Is this true?

**Comment by HakanSeven12** [comment] 2020-03-20 16:10
It's added to dev release: https://anaconda.org/freecad/pivy/files?version=0.6.6dev

**Comment by luzpaz** [comment] 2020-03-21 12:51
@HakanSeven12, I'm  confused, why are you directing me to the dev version? Are implying this feature was added ?

**Comment by HakanSeven12** [comment] 2020-03-21 12:56
Yes. It's accessible on pivy dev version.
